name: torch_18
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - pillow=6.0.0
  - python=3.7
  - pytorch=1.8.0=py3.7_cuda10.2_cudnn7.6.5_0
  - tensorboard=2.1
  - torchvision=0.9.0=py37_cu102
  - pip=20.0
  - pip:
    - opencv-python==4.5.5.62
    - natsort
    - tensorboardX
    - yacs
    - scikit-image
    - scikit-learn
    - pycocotools
    - matplotlib
    - tqdm
    - PyYAML
    - fvcore==0.1.5.post20210415
    - https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/torch1.8/detectron2-0.4%2Bcu102-cp37-cp37m-linux_x86_64.whl
    - cityscapesScripts==2.1.7
    - albumentations==0.5.2
    - kornia==0.5.0
    - imagecorruptions==1.1.2
    - pynvml==11.0.0
    - captum==0.4.0
    - ptflops==0.6.6
    - torchmetrics==0.6.2
